name: chatbot-production-stack

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "chatbot"
    restart: unless-stopped
    ports:
      - "${PORT}:${PORT}" # Automatically pulls the port from  .env file
    environment:
      - NODE_ENV=${NODE_ENV}
      - MONGODB_URI=${MONGODB_URI} # Dynamically injects your secure cloud string
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
